//
// Created by Zhou,Xuguang on 2018/12/18.
//

#ifndef BAIDUMAP_RENDERENGINE_RENDERSTATE_H
#define BAIDUMAP_RENDERENGINE_RENDERSTATE_H

#include "RenderDefine.h"

BAIDUMAP_RENDER_ENGINE_BEGIN

class RenderState {

};

BAIDUMAP_RENDER_ENGINE_END


#endif //RENDERENGINE_RENDERSTATE_H
